--! Estas son las tablas básicas para que la aplicación cree conversaciones, guarde mensajes y maneje asesores.
-- 1. Habilitar extensión para UUIDs (necesario para gen_random_uuid())
CREATE EXTENSION IF NOT EXISTS "pgcrypto";

-- 2. Tabla ADVISORS (Debe crearse primero porque otras dependen de ella)
CREATE TABLE public.advisors (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  name character varying(255) NOT NULL,
  phone_number character varying(20) NOT NULL,
  twilio_phone_number character varying(20) NOT NULL,
  is_active boolean NULL DEFAULT true,
  created_at timestamp without time zone NULL DEFAULT now(),
  CONSTRAINT advisors_pkey PRIMARY KEY (id),
  CONSTRAINT advisors_phone_number_key UNIQUE (phone_number),
  CONSTRAINT advisors_twilio_phone_number_key UNIQUE (twilio_phone_number)
) TABLESPACE pg_default;

-- 3. Tabla CHAT_HISTORY (Depende de advisors)
CREATE TABLE public.chat_history (
  id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  client_number text NULL,
  messages_backup jsonb NULL,
  audio boolean NULL DEFAULT false,
  client_name text NULL,
  chat_on boolean NULL DEFAULT false,
  chat_status text NULL DEFAULT 'open'::text,
  agent_name text NULL DEFAULT 'asadores'::text,
  nit text NULL,
  notes text NULL,
  email text NULL,
  company text NULL,
  position text NULL,
  category text NULL,
  classification text NULL,
  credit text NULL,
  address text NULL,
  city text NULL,
  notified_no_reply boolean NULL DEFAULT false,
  notified_out_of_hours boolean NULL DEFAULT false,
  notified_out_afternoon boolean NULL DEFAULT false,
  origin character varying NULL,
  is_archived boolean NULL DEFAULT false,
  advisor_id uuid NULL,
  CONSTRAINT chat_history_pkey PRIMARY KEY (id),
  CONSTRAINT chat_history_id_key UNIQUE (id),
  CONSTRAINT chat_history_advisor_id_fkey FOREIGN KEY (advisor_id) REFERENCES advisors (id)
) TABLESPACE pg_default;

-- Índices para chat_history
CREATE INDEX IF NOT EXISTS idx_chat_history_advisor_archived ON public.chat_history USING btree (advisor_id, is_archived) TABLESPACE pg_default;
CREATE INDEX IF NOT EXISTS idx_chat_history_advisor_id ON public.chat_history USING btree (advisor_id) TABLESPACE pg_default;
CREATE INDEX IF NOT EXISTS idx_chat_history_client_advisor ON public.chat_history USING btree (client_number, advisor_id) TABLESPACE pg_default;

-- 4. Tabla MESSAGES (Depende de chat_history y advisors)
CREATE TABLE public.messages (
  id serial NOT NULL,
  conversation_id bigint NULL,
  sender text NULL,
  message text NULL,
  url text NULL,
  type text NULL,
  status text NULL DEFAULT 'sent'::text,
  created_at timestamp with time zone NULL DEFAULT now(),
  read_at timestamp with time zone NULL,
  twilio_sid text NULL,
  file_name text NULL,
  delivered_at timestamp with time zone NULL,
  sent_at timestamp with time zone NULL,
  failed_at timestamp with time zone NULL,
  error_code text NULL,
  error_message text NULL,
  advisor_id uuid NULL,
  CONSTRAINT messages_pkey PRIMARY KEY (id),
  CONSTRAINT fk_conversation FOREIGN KEY (conversation_id) REFERENCES chat_history (id) ON DELETE CASCADE,
  CONSTRAINT messages_advisor_id_fkey FOREIGN KEY (advisor_id) REFERENCES advisors (id)
) TABLESPACE pg_default;

-- Índices para messages
CREATE INDEX IF NOT EXISTS idx_messages_conversation_advisor ON public.messages USING btree (conversation_id, advisor_id, created_at) TABLESPACE pg_default;
CREATE INDEX IF NOT EXISTS idx_messages_conversation_id ON public.messages USING btree (conversation_id) TABLESPACE pg_default;
CREATE INDEX IF NOT EXISTS idx_messages_twilio_sid ON public.messages USING btree (twilio_sid) TABLESPACE pg_default;
CREATE INDEX IF NOT EXISTS idx_messages_advisor_id ON public.messages USING btree (advisor_id) TABLESPACE pg_default;

-- 5. Tabla MESSAGE_STATUS_HISTORY (Depende de messages)
CREATE TABLE public.message_status_history (
  id bigserial NOT NULL,
  message_id integer NULL,
  twilio_sid text NOT NULL,
  status text NOT NULL,
  previous_status text NULL,
  error_code text NULL,
  error_message text NULL,
  raw_webhook jsonb NULL,
  created_at timestamp with time zone NULL DEFAULT now(),
  CONSTRAINT message_status_history_pkey PRIMARY KEY (id),
  CONSTRAINT message_status_history_message_id_fkey FOREIGN KEY (message_id) REFERENCES messages (id)
) TABLESPACE pg_default;

-- Índices para message_status_history
CREATE INDEX IF NOT EXISTS idx_status_history_twilio_sid ON public.message_status_history USING btree (twilio_sid) TABLESPACE pg_default;

--! Datos insertados de ejemplo
INSERT INTO public.items_catalog (name, category, unit, unit_cost) VALUES
-- MATERIALES (Precios extraídos de tus CSVs)
('Concrete', 'Material', 'cy', 200),       -- Costo recurrente en tus excels
('Rebar', 'Material', 'ea', 15),           -- Varilla
('Wire Mesh', 'Material', 'roll', 41),     -- Malla
('Poly', 'Material', 'roll', 225),         -- Plástico/Polietileno
('Gravel', 'Material', 'load', 1200),      -- Grava (Visto 900 y 1200, puse promedio alto)
('Forms (Lumber)', 'Material', 'ea', 16),  -- Formaleta/Madera
('Pipes', 'Material', 'ea', 200),          -- Tubería

-- EQUIPOS Y HERRAMIENTAS
('Dumpster Rental', 'Equipment', 'load', 350), -- Contenedor escombros
('Concrete Pump', 'Equipment', 'day', 1200),   -- Bomba de concreto
('Excavator/Tractor', 'Equipment', 'day', 300),
('Buggy', 'Equipment', 'day', 500),
('Saw Blades', 'Consumable', 'ea', 150),       -- Discos de corte
('Equipment Rentals', 'Equipment', 'day', 600), -- Alquiler genérico

-- MANO DE OBRA (LABOR)
('Saw Cut Labor', 'Labor', 'lf', 7.5),     -- Corte
('Demolition Labor', 'Labor', 'sqft', 6),  -- Demolición
('Pour Back Labor', 'Labor', 'sqft', 12),  -- Vaciado/Acabado (Promedio entre 5 y 15 según dificultad)
('Footing Labor', 'Labor', 'lf', 50),      -- Cimentación

-- SERVICIOS "TURNKEY" (Precios base para referencia rápida)
('Bollard Installation', 'Service', 'ea', 500), -- Bolardos
('Curb and Gutter', 'Service', 'lf', 19),       -- Bordillo y Cuneta
('Sidewalk', 'Service', 'sqft', 7);             -- Aceras